### PR TITLE
 Wait for XR before play

### PR DESCRIPTION
**Pull request by lmidang**
**Description:**
Fix for this [issue](https://nianticlabs.slack.com/archives/CD10ANGUA/p1722620626954869)

**Testing**

https://github.com/user-attachments/assets/c6272ec8-95dd-4e75-96e5-6eb79ebcf8f1

### CODE REVIEW

**Comment by cmbartschat** [comment]
Can you use the same commit message as https://github.com/8thwall/8frame/commit/db16b54f885be3eaee8ca2ca5ff69ab9418b613d so it's easier to track?

**Comment by cmbartschat** [comment]
If we revert to the aframe 1.5.0 commit and apply all the picks from before, are there any missing that this branch doesn't have?

**Comment by lmidang** [comment]
> If we revert to the aframe 1.5.0 commit and apply all the picks from before, are there any missing that this branch doesn't have?

which 1.5.0 commit?

**Comment by cmbartschat** [comment]
The commit corresponding with https://github.com/aframevr/aframe/releases/tag/v1.5.0 - 

https://github.com/aframevr/aframe/commit/7856a058266f0aab94c262284516a6f123abdb11

**Review by cmbartschat — APPROVED** [review]

**Review by yuyansong-8thwall — APPROVED** [review]
LGTM

**Comment by lmidang** [comment]
> The commit corresponding with https://github.com/aframevr/aframe/releases/tag/v1.5.0 -
> 
> [aframevr@7856a05](https://github.com/aframevr/aframe/commit/7856a058266f0aab94c262284516a6f123abdb11)

I think this branch was pulled after the commit and added some changes, so I don't think it's missing anything from 1.5.0

**Pull request merged**
